### ISSUE TITLE
Typescript error when integrating with agora-rtc-sdk-ng

### ISSUE THREAD

**Issue by yinjs** [AgoraIO-Extensions/agora-rtc-react#178]
### What kind of problem do you need help?

Typescript error when integrating with agora-rtc-sdk-ng
<img width="1041" alt="Screenshot 2023-12-18 at 10 19 00" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/9780399/d72ac5fc-1218-4b2a-b187-b8ce80adf66c">

**Comment by hyrious** [comment]
I noticed `agora-rtc-sdk-ng` is bundled in `agora-rtc-react`, which means you should not install the former package and you should just import all your needed names from `agora-rtc-react`:

```ts
import AgoraRTC from 'agora-rtc-react'
```

@guoxianzhe Is this by design? If so you may update the README otherwise any internal change to `agora-rtc-sdk-ng` would break your example in README.

**Comment by yinjs** [comment]
@hyrious Thanks.  Works properly after import AgoraRTC from 'agora-rtc-react'. @hyrious @guoxianzhe Do you think it makes more sense to treat 'agora-rtc-sdk-ng' as a peer dependency?

`import AgoraRTC, { AgoraRTCProvider } from "agora-rtc-react";`

**Comment by guoxianzhe** [comment]
@yinjs please check https://github.com/AgoraIO-Extensions/agora-rtc-react/issues/146
